# Generated by Django 5.2.4 on 2025-07-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvaiablePlatformServiceByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('platform_home_url', models.URLField()),
                ('platform_themeColorCode', models.CharField(max_length=55)),
                ('streamingOptionTypes', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_man.country')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightThemeImage', models.ImageField(blank=True, null=True, upload_to='platform/img/lightThemeImage/')),
                ('darkThemeImage', models.ImageField(blank=True, null=True, upload_to='platform/img/darkThemeImage/')),
                ('whiteImage', models.ImageField(blank=True, null=True, upload_to='platform/img/whiteImage/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='api_man.avaiableplatformservicebycountry')),
            ],
        ),
    ]
